group: travis_latest
language: python
cache: pip

matrix:
  include:
    - python: 2.7
      env: NO_REMOTE=true, TOXENV=py27
    - python: 3.6
      env: NO_REMOTE=true, TOXENV=py36

install: pip install flake8 tox -r requirements.txt
  
before_script:
  - flake8 --bug-report
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --ignore=E1,E2,E3,W293,W291,E501,C901 --exit-zero --max-complexity=10 --max-line-length=127 --statistics

script: tox
