# GitHub Action workflow to build and run Impacket's tests
#

name: Build and test Impacket

on: [push, pull_request]

env:
  NO_REMOTE: true
  DOCKER_TAG: impacket:latests

jobs:
  test:
    name: Run unit tests and build wheel
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        tox-env: [py27, py36, py37, py38, py39]
        experimental: [false]
        include:
          - tox-env: py27
            python-version: 2.7
          - tox-env: py36
            python-version: 3.6
          - tox-env: py37
            python-version: 3.7
          - tox-env: py38
            python-version: 3.8
          - tox-env: py39
            python-version: 3.9
            experimental: true
    env:
      TOXENV: ${{ matrix.tox-env }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - name: Checkout Impacket
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install flake8 tox -r requirements.txt

      - name: Check syntax errors
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Check PEP8 warnings
        run: |
          flake8 . --count --ignore=E1,E2,E3,E501,W291,W293 --exit-zero --max-complexity=65 --max-line-length=127 --statistics

      - name: Run unit tests
        run: |
          tox

      - name: Build wheel artifact
        run: |
          python setup.py bdist_wheel

  docker:
    name: Build docker image
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Impacket
        uses: actions/checkout@v2

      - name: Build docker image
        run: |
          docker build -t ${{ env.DOCKER_TAG }} .
